#!/bin/bash

CONF=vim
BACKUP_DIR="${HOME}/.shell-conf-backup"
CONF_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

DIR=$(locate .vimrc)

cp $DIR ./

mv .vimrc ./vim/vimrc 

#${CONF_DIR}install

# Link to proper files
#ln -s ${CONF_DIR} ${HOME}/.${CONF}
#echo "${CONF} directory installed."
#ln -s ${CONF_DIR}/vimrc ${HOME}/.vimrc
#echo "vimrc installed."
